`timescale 1ns/1ps
/*
*******************************************************************************************************
File name   : key_expansion.sv
Module name : key_expansion

Korean:
- AES-128 Key Expansion에서 "현재 round key"로부터 "다음 round key"를 생성하는 모듈입니다.
- 입력 key_in은 현재 128-bit round key입니다.
- 입력 round는 다음 key를 만들 때 사용할 Rcon 번호입니다.
  예: key_in = RoundKey0, round = 1이면 RoundKey1을 생성합니다.
      key_in = RoundKey1, round = 2이면 RoundKey2를 생성합니다.
- AES-128에서는 총 11개의 round key가 필요합니다.
  RoundKey0는 original key이고, RoundKey1~RoundKey10은 key expansion으로 생성됩니다.
- 이 모듈은 조합논리(combinational logic)이므로 clk/reset이 필요 없습니다.

English:
- This module generates the next AES-128 round key from the current round key.
- key_in is the current 128-bit round key.
- round selects the Rcon value used to generate the next key.
  Example: key_in = RoundKey0 and round = 1 generates RoundKey1.
           key_in = RoundKey1 and round = 2 generates RoundKey2.
- AES-128 requires 11 round keys in total.
  RoundKey0 is the original key, and RoundKey1~RoundKey10 are generated by key expansion.
- This is combinational logic, so no clock or reset is required.

Important byte/word order:
- key_in[127:96] = w0
- key_in[95:64]  = w1
- key_in[63:32]  = w2
- key_in[31:0]   = w3
- key_out = {w4, w5, w6, w7}

This ordering is consistent with the AES state vector used in the previous modules.
*******************************************************************************************************
*/

module key_expansion (
    input  wire [127:0] key_in,    // Korean: 현재 128-bit round key / English: current 128-bit round key
    input  wire [3:0]   round,     // Korean: Rcon 선택용 round 번호 1~10 / English: round number for Rcon selection, 1~10
    output wire [127:0] key_out    // Korean: 다음 128-bit round key / English: next 128-bit round key
);

    /*
    Korean:
    - AES-128 key는 4개의 32-bit word로 나눕니다.
    - 예: original key = 2b7e1516 28aed2a6 abf71588 09cf4f3c
      w0 = 2b7e1516
      w1 = 28aed2a6
      w2 = abf71588
      w3 = 09cf4f3c

    English:
    - The AES-128 key is split into four 32-bit words.
    */
    wire [31:0] w0;
    wire [31:0] w1;
    wire [31:0] w2;
    wire [31:0] w3;

    assign w0 = key_in[127:96];
    assign w1 = key_in[95:64];
    assign w2 = key_in[63:32];
    assign w3 = key_in[31:0];

    /*
    Korean:
    - 다음 key의 word들입니다.
    - w4 = w0 XOR SubWord(RotWord(w3)) XOR Rcon
    - w5 = w1 XOR w4
    - w6 = w2 XOR w5
    - w7 = w3 XOR w6

    English:
    - These are the next key words.
    */
    wire [31:0] w4;
    wire [31:0] w5;
    wire [31:0] w6;
    wire [31:0] w7;

    /*
    Korean:
    - RotWord(w3)를 수행합니다.
    - w3 = {byte0, byte1, byte2, byte3}라면
      RotWord(w3) = {byte1, byte2, byte3, byte0}

    English:
    - Perform RotWord on w3.
    - If w3 = {byte0, byte1, byte2, byte3},
      RotWord(w3) = {byte1, byte2, byte3, byte0}.
    */
    wire [7:0] rot_b0;
    wire [7:0] rot_b1;
    wire [7:0] rot_b2;
    wire [7:0] rot_b3;

    assign rot_b0 = w3[23:16];
    assign rot_b1 = w3[15:8];
    assign rot_b2 = w3[7:0];
    assign rot_b3 = w3[31:24];

    /*
    Korean:
    - SubWord는 RotWord 결과의 각 byte에 S-box를 적용하는 단계입니다.
    - 따라서 sbox module 4개를 사용합니다.

    English:
    - SubWord applies the AES S-box to each byte of the RotWord result.
    - Therefore, four sbox modules are used.
    */
    wire [7:0] sub_b0;
    wire [7:0] sub_b1;
    wire [7:0] sub_b2;
    wire [7:0] sub_b3;

    sbox sbox_key_0 (.in_byte(rot_b0), .out_byte(sub_b0));
    sbox sbox_key_1 (.in_byte(rot_b1), .out_byte(sub_b1));
    sbox sbox_key_2 (.in_byte(rot_b2), .out_byte(sub_b2));
    sbox sbox_key_3 (.in_byte(rot_b3), .out_byte(sub_b3));

    /*
    Korean:
    - Rcon은 round마다 정해진 8-bit 값입니다.
    - AES-128에서는 round 1~10까지 사용합니다.
    - 32-bit로 적용할 때는 {Rcon, 24'h000000} 형태입니다.

    English:
    - Rcon is a fixed 8-bit value for each round.
    - AES-128 uses rounds 1 to 10.
    - In a 32-bit word, it is applied as {Rcon, 24'h000000}.
    */
    wire [7:0] rcon_value;

    assign rcon_value = get_rcon(round);

    /*
    Korean:
    - temp_word = SubWord(RotWord(w3)) XOR Rcon
    - Rcon은 첫 번째 byte에만 XOR됩니다.

    English:
    - temp_word = SubWord(RotWord(w3)) XOR Rcon.
    - Rcon is XORed only with the first byte.
    */
    wire [31:0] temp_word;

    assign temp_word = {
        sub_b0 ^ rcon_value,
        sub_b1,
        sub_b2,
        sub_b3
    };

    /*
    Korean:
    - AES-128 key expansion 공식입니다.
    - w4를 먼저 만들고, 그 다음 w5, w6, w7을 순서대로 만듭니다.

    English:
    - AES-128 key expansion equations.
    - w4 is generated first, then w5, w6, and w7.
    */
    assign w4 = w0 ^ temp_word;
    assign w5 = w1 ^ w4;
    assign w6 = w2 ^ w5;
    assign w7 = w3 ^ w6;

    /*
    Korean:
    - 다음 round key를 128-bit로 묶어서 출력합니다.
    - 이 순서는 AES state와 AddRoundKey에서 쓰는 column-major vector 순서와 맞춥니다.

    English:
    - Pack the next round key into a 128-bit output.
    - This ordering matches the column-major vector order used by the AES state and AddRoundKey.
    */
    assign key_out = {w4, w5, w6, w7};

    /*
    Korean:
    - round 번호에 따라 Rcon 값을 반환하는 function입니다.
    - round가 1~10이 아니면 00을 반환합니다.

    English:
    - This function returns the Rcon value for each round.
    - If round is not 1~10, it returns 00.
    */
    function [7:0] get_rcon;
        input [3:0] r;
        begin
            case (r)
                4'd1:  get_rcon = 8'h01;
                4'd2:  get_rcon = 8'h02;
                4'd3:  get_rcon = 8'h04;
                4'd4:  get_rcon = 8'h08;
                4'd5:  get_rcon = 8'h10;
                4'd6:  get_rcon = 8'h20;
                4'd7:  get_rcon = 8'h40;
                4'd8:  get_rcon = 8'h80;
                4'd9:  get_rcon = 8'h1b;
                4'd10: get_rcon = 8'h36;
                default: get_rcon = 8'h00;
            endcase
        end
    endfunction

endmodule
